In [1]:
import numpy as np

# 1. Create a 3x3x3 array with random values 

In [17]:
a = np.random.rand(3, 3, 3)
a

array([[[0.56862087, 0.46379585, 0.6696768 ],
        [0.40756943, 0.34339974, 0.78859947],
        [0.17636615, 0.29210567, 0.68831625]],

       [[0.62967754, 0.09371811, 0.96288763],
        [0.22328278, 0.38449025, 0.79443115],
        [0.43445303, 0.90780123, 0.58642579]],

       [[0.49784815, 0.76449145, 0.56522141],
        [0.58329024, 0.89837023, 0.21896703],
        [0.75602891, 0.28449422, 0.94591235]]])

# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [15]:
a = np.zeros((5, 5))
a[1:, 0] = 1
a[2:, 1] = 2
a[3:, 2] = 3
a[4:, 3] = 4
a

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 2., 0., 0., 0.],
       [1., 2., 3., 0., 0.],
       [1., 2., 3., 4., 0.]])

# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [11]:
a = np.zeros((8, 8))
a

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [13]:
a[::2, ::2] = 1
a[1::2, 1::2] = 1
a

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

# 4. Normalize a 5x5 random matrix

In [19]:
m = np.random.rand(5, 5)
norm = np.linalg.norm(m)
m_norm = m / norm
m_norm

array([[0.19031846, 0.09269308, 0.29610504, 0.0342057 , 0.05234356],
       [0.21208708, 0.01516912, 0.20585476, 0.23274563, 0.22888037],
       [0.01385623, 0.18373965, 0.18121632, 0.33862689, 0.03862029],
       [0.0694497 , 0.29781223, 0.08792156, 0.33963464, 0.16593765],
       [0.34296645, 0.0825353 , 0.16818625, 0.06739877, 0.29172536]])

# 5.  How to find common values between two arrays?

In [21]:
a = [[10, 20, 30], [40, 50, 60]]
b = [[20, 40], [60, 80]]
c = np.intersect1d(a, b)
c

array([20, 40, 60])

# 6.How to get the dates of yesterday, today and tomorrow?

In [22]:
today = np.datetime64('today', 'D')
print("Today: ",today)
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Today:  2020-07-28
Yestraday:  2020-07-27
Tomorrow:  2020-07-29


# 7. Consider two random array A and B, check if they are equal

In [25]:
a = [[10, 20, 30], [40, 50, 60]]
b = [[20, 40, 100], [60, 80, 200]]
c = [[10, 20, 30], [40, 50, 60]]
print('are a and b equal:', a == b)
print('are a and c equal:', a == c)

are a and b equal: False
are a and c equal: True


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [27]:
v = np.random.rand(10, 1)
v

array([[0.1727118 ],
       [0.98524507],
       [0.05382922],
       [0.60992492],
       [0.73581661],
       [0.72426938],
       [0.51663961],
       [0.71071478],
       [0.08403739],
       [0.74332122]])

In [34]:
i, j = np.where(v == np.max(v))
v[i, j] = 0
v

array([[0.1727118 ],
       [0.        ],
       [0.05382922],
       [0.60992492],
       [0.73581661],
       [0.72426938],
       [0.51663961],
       [0.71071478],
       [0.08403739],
       [0.74332122]])

# 9. How to print all the values of an array?

In [38]:
for i in v:
    print(i)

[0.1727118]
[0.]
[0.05382922]
[0.60992492]
[0.73581661]
[0.72426938]
[0.51663961]
[0.71071478]
[0.08403739]
[0.74332122]


# 10.Subtract the mean of each row of a matrix

In [62]:
m = np.random.randint(1, 100,(3, 3), dtype='int64')
m

array([[44, 44, 75],
       [28, 31, 47],
       [16, 93, 21]], dtype=int64)

In [68]:
mean = np.mean(m, axis=1).reshape(3, 1)
mean

array([[54.33333333],
       [35.33333333],
       [43.33333333]])

In [69]:
m - mean

array([[-10.33333333, -10.33333333,  20.66666667],
       [ -7.33333333,  -4.33333333,  11.66666667],
       [-27.33333333,  49.66666667, -22.33333333]])

# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [42]:
v = np.random.rand(10, 1)
v

array([[0.52876071],
       [0.41804229],
       [0.63207613],
       [0.6301032 ],
       [0.351588  ],
       [0.48425833],
       [0.08700503],
       [0.71358181],
       [0.1250565 ],
       [0.8053309 ]])

In [43]:
ind = np.random.randint(0,len(v),(v.shape[0]), dtype='int64')
ind

array([6, 0, 1, 3, 0, 6, 3, 3, 6, 9], dtype=int64)

In [45]:
for i in set(ind):
    v[i] += 1
print(v)

[[1.52876071]
 [1.41804229]
 [0.63207613]
 [1.6301032 ]
 [0.351588  ]
 [0.48425833]
 [1.08700503]
 [0.71358181]
 [0.1250565 ]
 [1.8053309 ]]


# 12.How to get the diagonal of a dot product?

In [46]:
a = [[1, 0], [0, 1]]
b = [[4, 1], [2, 2]]
np.dot(a, b)

array([[4, 1],
       [2, 2]])

In [47]:
np.diag(np.dot(a, b))

array([4, 2])

# 13.How to find the most frequent value in an array?

In [58]:
a = np.array([1, 2, 2, 3, 3, 3, 4, 4, 4, 4, 4])
print('the most frequent element:', np.argmax(np.bincount(a)))

the most frequent element: 4


# 14.How to get the n largest values of an array

In [61]:
a = np.array([int(x) for x in input("Enter an array: ").split()])
n = int(input("Enter n: "))
print('{} largest values are {}'.format(n, np.sort(a)[-n:]))
#print('{} largest values are {}'.format(n, a[np.argsort(a)[-n:]]))

Enter an array: 42 12 36 56 89 75 45 02 12
Enter n: 3
3 largest values are [56 75 89]


# 15.How to create a record array from a regular array?